export const allPosts = [
  
  // Google
  {
    companyId: 1,
    companyName: "Google",
    title: "Hiring AI Engineers",
    category: "Jobs",
    summary: "We are expanding our AI division and looking for brilliant engineers to join our mission.",
    source: "LinkedIn",
    date: "2025-04-26T09:00:00Z",
  },
  {
    companyId: 1,
    companyName: "Google",
    title: "Pixel 9 Launch",
    category: "Events",
    summary: "Google will reveal its newest Pixel devices at the upcoming annual technology showcase event.",
    source: "Company Website",
    date: "2025-04-20T17:30:00Z",
  },
  {
    companyId: 1,
    companyName: "Google",
    title: "Sustainability Update",
    category: "News",
    summary: "Learn about Google's new environmental initiatives to achieve carbon neutrality across all offices.",
    source: "Newsroom",
    date: "2025-04-18T11:15:00Z",
  },
  {
    companyId: 1,
    companyName: "Google",
    title: "New Internship Openings",
    category: "Jobs",
    summary: "Applications are now open for Google's next internship program, spanning multiple tech disciplines.",
    source: "Careers Page",
    date: "2025-04-25T13:00:00Z",
  },
  {
    companyId: 1,
    companyName: "Google",
    title: "Q1 Financial Results",
    category: "Financial",
    summary: "Strong growth across global markets has led to record-breaking earnings this quarter for Google.",
    source: "Investor Relations",
    date: "2025-04-15T08:45:00Z",
  },

  // Tesla
  {
    companyId: 2,
    companyName: "Tesla",
    title: "5M Cars Produced",
    category: "News",
    summary: "Tesla has officially produced 5 million vehicles globally, setting a new industry record milestone.",
    source: "Tesla Blog",
    date: "2025-04-21T10:00:00Z",
  },
  {
    companyId: 2,
    companyName: "Tesla",
    title: "Berlin Gigafactory Tours",
    category: "Events",
    summary: "Visit Tesla's Gigafactory in Berlin for an exclusive look inside their production process.",
    source: "Events Page",
    date: "2025-04-19T15:30:00Z",
  },
  {
    companyId: 2,
    companyName: "Tesla",
    title: "Hiring Engineers",
    category: "Jobs",
    summary: "We are hiring mechanical, electrical, and software engineers for our next-generation EVs.",
    source: "LinkedIn",
    date: "2025-04-22T09:15:00Z",
  },
  {
    companyId: 2,
    companyName: "Tesla",
    title: "Social Impact Report",
    category: "Social",
    summary: "Tesla launches new social programs supporting education, sustainability, and local communities.",
    source: "Impact Report",
    date: "2025-04-23T14:00:00Z",
  },
  {
    companyId: 2,
    companyName: "Tesla",
    title: "Q1 Earnings Released",
    category: "Financial",
    summary: "Tesla's Q1 earnings beat expectations, driven by record production and new model launches.",
    source: "Investor Relations",
    date: "2025-04-14T16:45:00Z",
  },

  // Adidas
  {
    companyId: 3,
    companyName: "Adidas",
    title: "UltraBoost 2025",
    category: "Products",
    summary: "Experience the future of running comfort with the revolutionary UltraBoost 2025 edition.",
    source: "Product Page",
    date: "2025-04-16T13:45:00Z",
  },
  {
    companyId: 3,
    companyName: "Adidas",
    title: "Beyoncé Collaboration",
    category: "Social",
    summary: "Adidas partners with Beyoncé for the latest Ivy Park collection inspired by bold creativity.",
    source: "Instagram",
    date: "2025-04-23T11:00:00Z",
  },
  {
    companyId: 3,
    companyName: "Adidas",
    title: "Marathon Sponsorship",
    category: "Events",
    summary: "Proud sponsor of this year's Berlin Marathon, empowering athletes around the world.",
    source: "Newsroom",
    date: "2025-04-17T10:00:00Z",
  },
  {
    companyId: 3,
    companyName: "Adidas",
    title: "Hiring Designers",
    category: "Jobs",
    summary: "Join our global design team to innovate the future of athletic and streetwear fashion.",
    source: "Careers Page",
    date: "2025-04-26T08:30:00Z",
  },
  {
    companyId: 3,
    companyName: "Adidas",
    title: "Financial Update",
    category: "Financial",
    summary: "Adidas posts strong quarterly results, driven by growth in the lifestyle and performance sectors.",
    source: "Investor Relations",
    date: "2025-04-13T09:00:00Z",
  },

  // UBS
  {
    companyId: 4,
    companyName: "UBS",
    title: "Credit Suisse Merger",
    category: "News",
    summary: "UBS finalizes historic merger with Credit Suisse, strengthening its global banking footprint.",
    source: "Press Release",
    date: "2025-04-14T07:30:00Z",
  },
  {
    companyId: 4,
    companyName: "UBS",
    title: "Investor Conference",
    category: "Events",
    summary: "UBS hosts its annual Global Wealth Management Conference featuring top financial leaders.",
    source: "Events Page",
    date: "2025-04-20T14:00:00Z",
  },
  {
    companyId: 4,
    companyName: "UBS",
    title: "Hiring Analysts",
    category: "Jobs",
    summary: "UBS is seeking talented analysts to join its fast-growing global investment banking team.",
    source: "LinkedIn",
    date: "2025-04-22T12:15:00Z",
  },
  {
    companyId: 4,
    companyName: "UBS",
    title: "Charity Drive",
    category: "Social",
    summary: "Supporting local communities through UBS's new global philanthropic and volunteer initiatives.",
    source: "CSR Report",
    date: "2025-04-18T11:30:00Z",
  },
  {
    companyId: 4,
    companyName: "UBS",
    title: "Financial Outlook",
    category: "Financial",
    summary: "UBS projects steady growth through diversified investments and emerging market expansion.",
    source: "Investor Outlook",
    date: "2025-04-16T10:15:00Z",
  },

  // Netflix
  {
    companyId: 5,
    companyName: "Netflix",
    title: "Future Earth Release",
    category: "News",
    summary: "Netflix announces the launch of 'Future Earth,' a new documentary series about sustainability.",
    source: "Netflix Newsroom",
    date: "2025-04-24T09:00:00Z",
  },
  {
    companyId: 5,
    companyName: "Netflix",
    title: "Gaming Expansion",
    category: "Financial",
    summary: "Netflix invests heavily into mobile gaming, acquiring several indie studios this quarter.",
    source: "Investor Update",
    date: "2025-04-21T10:30:00Z",
  },
  {
    companyId: 5,
    companyName: "Netflix",
    title: "Hiring Creatives",
    category: "Jobs",
    summary: "We are hiring storytellers, producers, and designers for upcoming original Netflix productions.",
    source: "Careers Page",
    date: "2025-04-25T15:00:00Z",
  },
  {
    companyId: 5,
    companyName: "Netflix",
    title: "Social Impact Films",
    category: "Social",
    summary: "Netflix releases a series of impactful films highlighting global social and cultural issues.",
    source: "Company Blog",
    date: "2025-04-22T14:45:00Z",
  },
  {
    companyId: 5,
    companyName: "Netflix",
    title: "Netflix Festival",
    category: "Events",
    summary: "Join the world's first Netflix Festival, celebrating creativity, innovation, and storytelling.",
    source: "Events Page",
    date: "2025-04-27T13:15:00Z",
  },
];
